const $=selector=>document.querySelector(selector),DAY_ORDER=[1,2,3,4,5,6,0];
// Development-only gate. Replace with secure server-side authentication before launch.
const ADMIN_USER='admin@remmybeautyplus.com',ADMIN_PASSWORD='remmy-demo-2026';
const esc=value=>String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
const niceDate=date=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(`${date}T12:00:00`));
const displayTime=time=>{const [h,m]=time.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`};
const formatDuration=hours=>`${Math.floor(hours)?`${Math.floor(hours)} hr${Math.floor(hours)!==1?'s':''}`:''}${hours%1?' 30 min':''}`;
function slugify(name){return `${name.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-${Date.now().toString().slice(-5)}`}

function renderDashboard(){const all=RemmyStore.getBookings(),today=new Date().toLocaleDateString('en-CA'),active=all.filter(item=>item.status!=='cancelled'),upcoming=active.filter(item=>item.date>=today);$('#todayLabel').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date());$('#stats').innerHTML=[[active.filter(item=>item.date===today).length,'Today'],[upcoming.length,'Upcoming'],[RemmyStore.getServices().filter(item=>item.available!==false).length,'Active services'],[RemmyStore.getBlockedDates().length,'Blocked dates']].map(([value,label])=>`<article class="stat"><span>${label}</span><b>${value}</b></article>`).join('');renderAppointments();renderServices();renderHours();renderBlocked()}
function renderAppointments(){const rows=RemmyStore.getBookings().sort((a,b)=>(a.date+a.startTime).localeCompare(b.date+b.startTime));$('#appointmentsBody').innerHTML=rows.map(item=>`<tr><td><b>${esc(item.customerName)}</b><br>${esc(item.phone)}</td><td>${esc(item.service)}</td><td>${niceDate(item.date)}<br>${displayTime(item.startTime)}</td><td>${formatDuration(item.duration)}</td><td>$${item.price}</td><td>$${item.deposit||0}</td><td><span class="status ${item.status}">${item.status}</span></td><td><button class="table-action" data-action="view" data-id="${item.id}">View</button><button class="table-action" data-action="calendar" data-id="${item.id}">Download</button><button class="table-action" data-action="google" data-id="${item.id}">Google</button><button class="table-action" data-action="complete" data-id="${item.id}">Complete</button><button class="table-action danger" data-action="cancel" data-id="${item.id}">Cancel</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No appointments yet.</td></tr>';$('#appointmentsBody').querySelectorAll('button').forEach(button=>button.onclick=()=>appointmentAction(button.dataset.action,button.dataset.id))}
function appointmentAction(action,id){const item=RemmyStore.getBookings().find(entry=>entry.id===id);if(!item)return;if(action==='calendar'){downloadAppointmentCalendar(item);return}if(action==='google'){openGoogleCalendar(item);return}if(action==='view'){const dialog=$('#bookingDialog');$('#dialogContent').innerHTML=`<p class="eyebrow">${esc(item.id)}</p><h2>${esc(item.customerName)}</h2><p><b>${esc(item.service)}</b><br>${niceDate(item.date)}, ${displayTime(item.startTime)}–${displayTime(item.endTime)}</p><p>${esc(item.phone)}<br>${esc(item.email)}</p><p>${esc(item.notes||'No notes provided.')}</p><button class="btn rounded" onclick="downloadAppointmentCalendar(RemmyStore.getBookings().find(item=>item.id==='${item.id}'))">Download calendar event</button>`;dialog.showModal();return}action==='cancel'?RemmyStore.cancelBooking(id):RemmyStore.updateBooking(id,{status:'completed'});renderDashboard()}
function calendarDate(date){return date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}function calendarText(value){return String(value||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function downloadAppointmentCalendar(item){const start=new Date(`${item.date}T${item.startTime}:00`),end=new Date(`${item.date}T${item.endTime}:00`),settings=RemmyStore.getReminderSettings(),hours=settings.hoursBefore==='custom'?Number(settings.customHours||24):Number(settings.hoursBefore),description=`Customer: ${item.customerName}\nService: ${item.service}\nDuration: ${formatDuration(item.duration)}\nPhone: ${item.phone}\nEmail: ${item.email||''}\nBooking reference: ${item.id}`,alarm=hours>0?`BEGIN:VALARM\r\nTRIGGER:-PT${hours}H\r\nACTION:DISPLAY\r\nDESCRIPTION:Upcoming Remmybeautyplus appointment\r\nEND:VALARM\r\n`:'';const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Remmybeautyplus//Appointments//EN\r\nBEGIN:VEVENT\r\nUID:${item.id}@remmybeautyplus.com\r\nDTSTAMP:${calendarDate(new Date())}\r\nDTSTART:${calendarDate(start)}\r\nDTEND:${calendarDate(end)}\r\nSUMMARY:${calendarText(`${item.customerName} — ${item.service}`)}\r\nDESCRIPTION:${calendarText(description)}\r\nLOCATION:Remmybeautyplus\r\n${alarm}END:VEVENT\r\nEND:VCALENDAR`;const url=URL.createObjectURL(new Blob([ics],{type:'text/calendar'})),link=document.createElement('a');link.href=url;link.download=`${item.id}.ics`;link.click();URL.revokeObjectURL(url)}
function openGoogleCalendar(item){const start=new Date(`${item.date}T${item.startTime}:00`),end=new Date(`${item.date}T${item.endTime}:00`),details=`Customer: ${item.customerName}\nDuration: ${formatDuration(item.duration)}\nPhone: ${item.phone}\nEmail: ${item.email||''}\nBooking reference: ${item.id}`,params=new URLSearchParams({action:'TEMPLATE',text:`${item.customerName} — ${item.service}`,dates:`${calendarDate(start)}/${calendarDate(end)}`,details,location:'Remmybeautyplus'});window.open(`https://calendar.google.com/calendar/render?${params}`,'_blank','noopener')}

function renderServices(){const items=RemmyStore.getServices();$('#adminServices').innerHTML=items.map(item=>`<article class="admin-service ${item.available===false?'disabled':''}"><img src="${esc(item.image)}" alt=""><div><h3>${esc(item.name)}</h3><p>$${item.price} · ${formatDuration(item.duration)} · $${item.deposit??30} deposit</p><small>${esc(item.description||'No description')}</small></div><label class="switch"><input type="checkbox" data-toggle="${item.id}" ${item.available!==false?'checked':''}><i></i><span>${item.available!==false?'On':'Off'}</span></label><div class="service-actions"><button data-edit="${item.id}">Edit</button><button class="danger" data-delete="${item.id}">Delete</button></div></article>`).join('');$('#adminServices').querySelectorAll('[data-toggle]').forEach(input=>input.onchange=()=>{RemmyStore.saveService({id:input.dataset.toggle,available:input.checked});renderDashboard()});$('#adminServices').querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>openServiceDialog(items.find(item=>item.id===button.dataset.edit)));$('#adminServices').querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>{const item=items.find(entry=>entry.id===button.dataset.delete);if(confirm(`Delete ${item.name}? This cannot be undone.`)){RemmyStore.deleteService(item.id);renderDashboard()}})}
function openServiceDialog(service=null){const form=$('#serviceForm');form.reset();$('#serviceFormEyebrow').textContent=service?'Edit service':'New service';$('#serviceFormTitle').textContent=service?'Edit Service':'Add New Service';if(service){for(const key of ['id','name','image','price','duration','description'])form.elements[key].value=service[key]??'';form.deposit.value=service.deposit??30;form.available.checked=service.available!==false}else{form.id.value='';form.image.value='images/remmy-hero.webp';form.duration.value='2';form.deposit.value='30';form.available.checked=true}updatePreview();$('#serviceDialog').showModal()}
function updatePreview(){$('#serviceImagePreview').src=$('#serviceForm').image.value||'images/remmy-hero.webp'}
$('#serviceForm').elements.price.closest('label').insertAdjacentHTML('afterend','<label>Deposit amount ($) *<input name="deposit" type="number" min="0" step="1" value="30" required></label>');
$('#serviceForm').image.addEventListener('input',updatePreview);$('#serviceImagePreview').onerror=()=>{$('#serviceImagePreview').src='images/remmy-hero.webp'};$('#serviceForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);RemmyStore.saveService({id:data.get('id')||slugify(data.get('name')),name:data.get('name').trim(),image:data.get('image').trim(),price:Number(data.get('price')),deposit:Number(data.get('deposit')),duration:Number(data.get('duration')),description:data.get('description').trim(),available:data.get('available')==='on'});$('#serviceDialog').close();renderDashboard()});$('#addServiceBtn').onclick=()=>openServiceDialog();$('#serviceDialog .dialog-close').onclick=()=>$('#serviceDialog').close();

function renderHours(){const hours=RemmyStore.getBusinessHours();$('#hoursList').innerHTML=DAY_ORDER.map(day=>{const item=hours[day];return `<article class="hours-row" data-day="${day}"><b>${item.name}</b><label class="switch"><input name="available" type="checkbox" ${item.available?'checked':''}><i></i><span>${item.available?'On':'Off'}</span></label><label>Start<input name="start" type="time" value="${item.start}"></label><label>End<input name="end" type="time" value="${item.end}"></label><label class="custom-times">Available start times<input name="times" value="${(item.times||[]).join(', ')}" placeholder="Hourly (automatic)"></label></article>`}).join('')}
$('#saveHoursBtn').onclick=()=>{const hours=RemmyStore.getBusinessHours();document.querySelectorAll('.hours-row').forEach(row=>{const day=row.dataset.day;hours[day]={...hours[day],available:row.querySelector('[name="available"]').checked,start:row.querySelector('[name="start"]').value,end:row.querySelector('[name="end"]').value,times:row.querySelector('[name="times"]').value.split(',').map(value=>value.trim()).filter(value=>/^([01]\d|2[0-3]):[0-5]\d$/.test(value)).sort()}});RemmyStore.saveBusinessHours(hours);$('#hoursMessage').textContent='Booking availability saved.';renderDashboard();setTimeout(()=>$('#hoursMessage').textContent='',2500)};
$('#blockDateForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);RemmyStore.blockDate(data.get('date'),data.get('reason'));event.target.reset();renderDashboard()});function renderBlocked(){const items=RemmyStore.getBlockedDates();$('#blockedList').innerHTML=items.map(item=>`<span class="blocked-item"><b>${niceDate(item.date)}</b> · ${esc(item.reason)} <button data-date="${item.date}">Remove block</button></span>`).join('')||'<p class="empty">No blocked dates.</p>';$('#blockedList').querySelectorAll('button').forEach(button=>button.onclick=()=>{RemmyStore.unblockDate(button.dataset.date);renderDashboard()})}
function initializeAdmin(){
  const dashboard=$('.owner-dashboard');
  $('.admin-nav nav').insertAdjacentHTML('beforeend','<a href="#campaigns">Email Campaigns</a><a href="#reminders">Calendar & Reminders</a>');
  $('.admin-main').insertAdjacentHTML('beforeend',`<section class="admin-panel" id="reminders"><div class="panel-head"><div><p class="eyebrow">Automation settings</p><h2>Calendar & Reminders</h2><p>Choose how reminders should work when the scheduled backend is connected.</p></div><span class="integration-status"><i></i> Calendar export ready</span></div><form id="reminderForm" class="reminder-settings"><label class="setting-card"><span><b>Customer reminders</b><small>Remind clients before appointments</small></span><span class="switch"><input name="customerEnabled" type="checkbox"><i></i></span></label><label class="setting-card"><span><b>Admin reminders</b><small>Remind the hairstylist before appointments</small></span><span class="switch"><input name="adminEnabled" type="checkbox"><i></i></span></label><label class="setting-card"><span><b>Email reminders</b><small>Future email provider</small></span><span class="switch"><input name="emailEnabled" type="checkbox"><i></i></span></label><label class="setting-card"><span><b>SMS reminders</b><small>Future Twilio scheduled messages</small></span><span class="switch"><input name="smsEnabled" type="checkbox"><i></i></span></label><label>Reminder time<select name="hoursBefore"><option value="24">24 hours before</option><option value="2">2 hours before</option><option value="48">48 hours before</option><option value="custom">Custom</option></select></label><label>Custom hours before<input name="customHours" type="number" min="1" placeholder="e.g. 12"></label><button class="btn rounded" type="submit">Save reminder settings</button><p class="save-message" id="reminderMessage"></p></form><div class="prototype-note"><b>Prototype status</b><p>Calendar files work now. Email and SMS preferences are saved, but reminders are not sent yet. A future server scheduler will send them even when the website is closed.</p></div></section>`);
  $('.admin-main').insertAdjacentHTML('beforeend',`<section class="admin-panel" id="campaigns"><div class="panel-head"><div><p class="eyebrow">Client community</p><h2>Email Campaigns</h2><p>Send friendly news and discounts only to customers who opted in.</p></div><span class="subscriber-count"><b id="subscriberCount">0</b> subscribers</span></div><div class="campaign-layout"><form id="campaignForm" class="campaign-form"><label>Campaign subject<input name="subject" required placeholder="A special offer from Remmybeautyplus ✨"></label><label>Message<textarea name="message" rows="7" required placeholder="Hi beautiful! We have something special for you..."></textarea></label><div class="campaign-actions"><button class="btn rounded" type="submit">Open campaign in email app</button><button class="btn btn-outline rounded" id="exportSubscribers" type="button">Export subscribers</button></div><p class="save-message" id="campaignMessage"></p></form><div class="subscriber-panel"><h3>Opted-in clients</h3><div id="subscriberList"></div></div></div><div class="prototype-note"><b>Privacy-friendly prototype</b><p>Recipients open in BCC so clients cannot see one another’s addresses. Your email app sends the message only after you review and press Send. A future Resend integration can deliver larger campaigns and handle unsubscribe links.</p></div></section>`);
  setupCampaigns();setupReminderSettings();
  document.body.insertAdjacentHTML('afterbegin',`<section class="login-wrap" id="loginScreen"><a class="back-to-site" href="index.html">← Back to website</a><form class="login-card" id="loginForm"><a class="brand" href="index.html">Remmy<span>beautyplus</span></a><p class="eyebrow">Studio portal</p><h1>Welcome back.</h1><label>Email<input name="username" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="btn" type="submit">Sign in</button><p class="form-error" id="loginError" role="alert"></p><p class="demo-credentials"><b>Demo login</b><br>admin@remmybeautyplus.com<br>remmy-demo-2026</p></form></section>`);
  dashboard.classList.add('hidden');
  const openDashboard=()=>{$('#loginScreen').classList.add('hidden');dashboard.classList.remove('hidden');renderDashboard()};
  if(sessionStorage.getItem('remmy_admin')==='true')openDashboard();
  $('#loginForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);if(data.get('username').trim().toLowerCase()===ADMIN_USER&&data.get('password')===ADMIN_PASSWORD){sessionStorage.setItem('remmy_admin','true');openDashboard()}else $('#loginError').textContent='Incorrect email or password.'});
  const signOut=document.createElement('button');signOut.className='admin-signout';signOut.textContent='Sign out';signOut.onclick=()=>{sessionStorage.removeItem('remmy_admin');location.reload()};$('.admin-nav').append(signOut);
}
function setupReminderSettings(){const form=$('#reminderForm'),settings=RemmyStore.getReminderSettings();for(const name of ['customerEnabled','adminEnabled','emailEnabled','smsEnabled'])form.elements[name].checked=Boolean(settings[name]);form.hoursBefore.value=settings.hoursBefore||'24';form.customHours.value=settings.customHours||'';form.addEventListener('submit',event=>{event.preventDefault();RemmyStore.saveReminderSettings({customerEnabled:form.customerEnabled.checked,adminEnabled:form.adminEnabled.checked,emailEnabled:form.emailEnabled.checked,smsEnabled:form.smsEnabled.checked,hoursBefore:form.hoursBefore.value,customHours:form.customHours.value});$('#reminderMessage').textContent='Reminder settings saved.';setTimeout(()=>$('#reminderMessage').textContent='',2500)})}
function getSubscribers(){const byEmail=new Map();RemmyStore.getBookings().filter(item=>item.marketingOptIn&&item.email).forEach(item=>byEmail.set(item.email.toLowerCase(),{name:item.customerName,email:item.email,consented:item.marketingConsentAt}));return [...byEmail.values()]}
function setupCampaigns(){const form=$('#campaignForm'),render=()=>{const subscribers=getSubscribers();$('#subscriberCount').textContent=subscribers.length;$('#subscriberList').innerHTML=subscribers.map(item=>`<article><span><b>${esc(item.name)}</b><small>${esc(item.email)}</small></span><i>Opted in</i></article>`).join('')||'<p class="empty">No clients have opted in yet.</p>'};render();form.addEventListener('submit',event=>{event.preventDefault();const subscribers=getSubscribers();if(!subscribers.length){$('#campaignMessage').textContent='There are no opted-in subscribers yet.';return}const data=new FormData(form),bcc=subscribers.map(item=>item.email).join(','),url=`mailto:?bcc=${encodeURIComponent(bcc)}&subject=${encodeURIComponent(data.get('subject'))}&body=${encodeURIComponent(data.get('message'))}`;if(url.length>7000){$('#campaignMessage').textContent='This audience is too large for the email app. Export the list and use an email provider.';return}window.location.href=url;$('#campaignMessage').textContent=`Campaign prepared for ${subscribers.length} opted-in client${subscribers.length===1?'':'s'}.`});$('#exportSubscribers').onclick=()=>{const subscribers=getSubscribers();if(!subscribers.length){$('#campaignMessage').textContent='There are no subscribers to export.';return}const csv=['Name,Email,Consent date',...subscribers.map(item=>[item.name,item.email,item.consented||''].map(value=>`"${String(value).replace(/"/g,'""')}"`).join(','))].join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),link=document.createElement('a');link.href=url;link.download='remmybeautyplus-subscribers.csv';link.click();URL.revokeObjectURL(url)}}
$('.booking-dialog-close').onclick=()=>$('#bookingDialog').close();initializeAdmin();
