const state={step:1,service:null,date:null,time:null,paymentMethod:'card'};
const $=selector=>document.querySelector(selector),form=$('#bookingForm'),steps=[...document.querySelectorAll('.form-step')];
const minutesToTime=total=>`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`;
const endTime=(start,duration)=>{const [h,m]=start.split(':').map(Number);return minutesToTime(h*60+m+duration*60)};
const overlaps=(aStart,aEnd,bStart,bEnd)=>aStart<bEnd&&aEnd>bStart;
const saleIsActive=service=>{const today=new Date().toLocaleDateString('en-CA');return Boolean(service.saleActive&&Number(service.salePrice)>0&&(!service.saleStartDate||today>=service.saleStartDate)&&(!service.saleEndDate||today<=service.saleEndDate))};
const servicePrice=service=>saleIsActive(service)?Number(service.salePrice):Number(service.regularPrice??service.price);

function isTimeAvailable(date,startTime,duration){
  const end=endTime(startTime,duration);
  return !RemmyStore.getBookings().filter(b=>b.status!=='cancelled'&&b.date===date).some(b=>overlaps(startTime,end,b.startTime,b.endTime));
}
function getAvailableTimes(date,duration){
  const hours=RemmyStore.getBusinessHours()[new Date(`${date}T12:00:00`).getDay()];
  if(!hours?.available||RemmyStore.getBlockedDates().some(item=>item.date===date))return[];
  const [openH,openM]=hours.start.split(':').map(Number),[closeH,closeM]=hours.end.split(':').map(Number),custom=hours.times||[];
  const available=[],now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
  const candidates=custom.length?custom:Array.from({length:Math.max(0,Math.ceil(((closeH*60+closeM)-(openH*60+openM))/60))},(_,i)=>minutesToTime(openH*60+openM+i*60));
  for(const time of candidates){const [h,m]=time.split(':').map(Number),minute=h*60+m;if(minute<openH*60+openM||minute+duration*60>closeH*60+closeM)continue;if(date===today&&minute<=now.getHours()*60+now.getMinutes())continue;if(isTimeAvailable(date,time,duration))available.push(time)}
  return available;
}
window.isTimeAvailable=isTimeAvailable;window.getAvailableTimes=getAvailableTimes;

function displayTime(time){const [h,m]=time.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function depositAmount(){return Number(state.service?.deposit??30)}
function niceDate(date){return new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date(`${date}T12:00:00`))}
function fail(message){$('#formError').textContent=message;return false}function clearError(){$('#formError').textContent=''}
function renderServices(){
  const requested=new URLSearchParams(location.search).get('service');
  const services=window.REMMY_SERVICES.filter(s=>s.available!==false);$('#bookingServices').innerHTML=services.map(s=>{const regular=Number(s.regularPrice??s.price),onSale=saleIsActive(s);return `<button type="button" class="service-option ${requested===s.id?'selected':''}" data-id="${s.id}"><img src="${s.image||RemmyStore.PLACEHOLDER_IMAGE}" alt="${s.name}"><span><b>${s.name}${onSale?' <em class="sale-badge inline">Sale</em>':''}</b><small class="booking-price">${onSale?`<del>$${regular}</del> <strong>$${servicePrice(s)}</strong>`:`$${regular}`} · ${formatDuration(s.duration)}</small></span><i>✓</i></button>`}).join('');$('#bookingServices').querySelectorAll('img').forEach(image=>image.onerror=()=>{image.onerror=null;image.src=RemmyStore.PLACEHOLDER_IMAGE});
  if(requested)state.service=services.find(s=>s.id===requested)||null;
  document.querySelectorAll('.service-option').forEach(button=>button.addEventListener('click',()=>{state.service=window.REMMY_SERVICES.find(s=>s.id===button.dataset.id);document.querySelectorAll('.service-option').forEach(item=>item.classList.toggle('selected',item===button));updateAside();clearError();setTimeout(()=>go(2),220)}));
  updateAside();return Boolean(state.service);
}
function renderQuickDates(){
  const dates=[];let cursor=new Date();cursor.setHours(12,0,0,0);
  while(dates.length<6){const local=new Date(cursor),value=`${local.getFullYear()}-${String(local.getMonth()+1).padStart(2,'0')}-${String(local.getDate()).padStart(2,'0')}`;if(getAvailableTimes(value,state.service.duration).length)dates.push({value,date:local});cursor.setDate(cursor.getDate()+1)}
  $('#quickDates').innerHTML=dates.map(item=>`<button type="button" class="quick-date ${state.date===item.value?'selected':''}" data-date="${item.value}"><small>${item.date.toLocaleDateString('en-US',{weekday:'short'})}</small><b>${item.date.getDate()}</b><span>${item.date.toLocaleDateString('en-US',{month:'short'})}</span></button>`).join('');
  document.querySelectorAll('.quick-date').forEach(button=>button.onclick=()=>{state.date=button.dataset.date;state.time=null;$('#bookingDate').value=state.date;document.querySelectorAll('.quick-date').forEach(item=>item.classList.toggle('selected',item===button));renderTimes();updateAside();clearError()});
}
function renderTimes(){
  const times=getAvailableTimes(state.date,state.service.duration);$('#timeSection').classList.remove('hidden');
  $('#timeGrid').innerHTML=times.map(time=>`<button type="button" class="time-btn" data-time="${time}">${displayTime(time)}</button>`).join('');
  $('#timeNote').textContent=times.length?'Choose one available start time.':'No appointments fit on this date. Please choose another.';
  document.querySelectorAll('.time-btn').forEach(button=>button.addEventListener('click',()=>{state.time=button.dataset.time;document.querySelectorAll('.time-btn').forEach(item=>item.classList.toggle('selected',item===button));updateAside();clearError()}));
}
function updateAside(){if(!state.service)return;$('#asideSelection').classList.remove('hidden');$('#asideService').textContent=state.service.name;$('#asideWhen').textContent=state.date?`${niceDate(state.date)}${state.time?` · ${displayTime(state.time)}`:''}`:'Choose a date and time';$('#asideDeposit').textContent=`$${depositAmount()} secures your appointment.`}
function validateStep(){
  if(state.step===1&&!state.service)return fail('Please select a service.');
  if(state.step===2){const input=$('#bookingDate'),hours=RemmyStore.getBusinessHours()[new Date(`${input.value}T12:00:00`).getDay()];if(!input.value)return fail('Please select a date.');if(input.value<input.min)return fail('Past dates cannot be booked.');if(!hours?.available)return fail('The studio is closed on that day.');if(RemmyStore.getBlockedDates().some(item=>item.date===input.value))return fail('That date is unavailable.');if(!state.time)return fail('Please select an available time.');}
  if(state.step===3){for(const input of form.querySelectorAll('[data-step="3"] input[required]'))if(!input.checkValidity())return fail(input.type==='email'?'Enter a valid email address.':'Complete all required fields.');}
  return true;
}
function go(step){state.step=step;steps.forEach(item=>item.classList.toggle('active',+item.dataset.step===step));document.querySelectorAll('.progress-labels span').forEach((item,index)=>item.classList.toggle('active',index<step));$('#progressFill').style.width=`${step*25}%`;$('#backBtn').classList.toggle('hidden',step===1);$('#nextBtn').classList.toggle('hidden',step===4);$('#payBtn').classList.toggle('hidden',step!==4);$('#payBtn').textContent=`Pay $${depositAmount()} Deposit`;if(step===2&&state.service)renderQuickDates();if(step===4)renderSummary();clearError();scrollTo({top:0,behavior:'smooth'})}
function customerName(){return `${form.firstName.value} ${form.lastName.value}`.trim()}
function renderSummary(target='#bookingSummary'){const s=state.service,deposit=depositAmount(),price=servicePrice(s),regular=Number(s.regularPrice??s.price),onSale=saleIsActive(s);$(target).innerHTML=`<div class="summary-feature"><small>Service</small><strong>${s.name}</strong><span>${niceDate(state.date)} · ${displayTime(state.time)}</span></div><div class="summary-row"><span>Duration</span><b>${formatDuration(s.duration)}</b></div><div class="summary-row"><span>Service price</span><b class="summary-price">${onSale?`<del>$${regular}</del> <strong>$${price}</strong>`:`$${price}`}</b></div><div class="summary-row"><span>Deposit due today</span><b>$${deposit}</b></div><div class="summary-row total"><span>Remaining balance</span><b>$${Math.max(0,price-deposit)}</b></div>${target==='#bookingSummary'?`<div class="summary-row"><span>Customer</span><b>${customerName()}</b></div>`:''}`;const policyDeposit=document.querySelector('.policy-brief li');if(policyDeposit)policyDeposit.textContent=`A $${deposit} non-refundable deposit is required to secure your appointment.`}
function makeReference(){return `RBP-${Math.floor(1000+Math.random()*9000)}`}
function paymentLabel(method){return({apple_pay:'Apple Pay',google_pay:'Google Pay',card:'Debit / Credit Card'})[method]||'Not selected'}
function showPaymentMessage(message,type='pending'){const box=$('#paymentMessage');box.textContent=message;box.className=`payment-feedback ${type}`}
function selectPaymentMethod(method){state.paymentMethod=method;document.querySelectorAll('[data-payment-method]').forEach(button=>{const selected=button.dataset.paymentMethod===method;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected))});$('#stripePaymentElement').classList.toggle('hidden',method!=='card');showPaymentMessage(`${paymentLabel(method)} selected. Secure payment activation is coming soon.`)}
function setupPaymentMethods(){const apple=$('.apple-pay'),google=$('.google-pay'),appleSupported=Boolean(window.ApplePaySession&&window.ApplePaySession.canMakePayments?.());apple.classList.remove('hidden');google.classList.remove('hidden');apple.classList.toggle('wallet-unsupported',!appleSupported);apple.title=appleSupported?'Apple Pay is supported on this device':'Apple Pay will activate here after Stripe verifies browser and wallet support';$('#applePayNote').classList.toggle('hidden',appleSupported);document.querySelectorAll('[data-payment-method]').forEach(button=>button.addEventListener('click',()=>selectPaymentMethod(button.dataset.paymentMethod)));selectPaymentMethod('card')}
function buildBookingDraft(){const data=new FormData(form),marketingOptIn=data.get('marketingOptIn')==='on';return{id:makeReference(),serviceId:state.service.id,service:state.service.name,price:servicePrice(state.service),regularPrice:Number(state.service.regularPrice??state.service.price),saleApplied:saleIsActive(state.service),duration:state.service.duration,date:state.date,startTime:state.time,endTime:endTime(state.time,state.service.duration),customerName:customerName(),email:data.get('email'),phone:data.get('phone'),instagram:data.get('instagram'),notes:data.get('notes'),marketingOptIn,marketingConsentAt:marketingOptIn?new Date().toISOString():null,deposit:depositAmount(),paymentMethod:paymentLabel(state.paymentMethod),paymentStatus:'Pending',depositStatus:'pending',status:'pending-payment',createdAt:new Date().toISOString()}}
async function processDepositPayment(){/* STRIPE INTEGRATION POINT: mount Stripe Payment Element in #stripePaymentElement (or redirect to Stripe Checkout), create the PaymentIntent on a secure server, and return only the provider's safe result. Never send raw card fields to this application. */return{success:false,status:'Pending',message:'Secure online payments are not connected yet. No payment was charged and your appointment was not confirmed.'}}
function finalizePaidBooking(draft,payment){const booking={...draft,paymentMethod:payment.methodLabel||draft.paymentMethod,paymentStatus:'Paid',depositStatus:'paid',paymentProviderId:payment.id||null,status:'confirmed'};RemmyStore.saveBooking(booking);notifyStylist(booking);form.classList.add('hidden');$('#confirmation').classList.remove('hidden');$('#bookingRef').textContent=booking.id;renderSummary('#confirmationSummary');$('#googleCalendarBtn').href=createGoogleCalendarLink(booking);$('#icsCalendarBtn').onclick=()=>downloadICS(booking)}
async function notifyStylist(booking){try{return(await fetch('/api/notify-booking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(booking)})).ok}catch{return false}}
form.addEventListener('submit',async event=>{event.preventDefault();clearError();if(!form.policies.checked)return fail('Please agree to the booking policy.');if(!isTimeAvailable(state.date,state.time,state.service.duration))return fail('That time was just booked. Please choose another.');const button=$('#payBtn'),original=button.textContent;button.disabled=true;button.textContent='Preparing secure payment…';showPaymentMessage('Preparing secure checkout…','pending');try{const draft=buildBookingDraft(),payment=await processDepositPayment(draft);if(!payment.success){showPaymentMessage(payment.message,'error');fail(payment.message);return}finalizePaidBooking(draft,payment)}catch{const message='Payment could not be completed. Please try again.';showPaymentMessage(message,'error');fail(message)}finally{button.disabled=false;button.textContent=original}});
const calendarLocal=(date,time)=>`${date.replace(/-/g,'')}T${time.replace(':','')}00`,calendarStamp=date=>date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
function calendarDescription(booking){return `Client Name: ${booking.customerName}\nService: ${booking.service}\nPhone Number: ${booking.phone}\nEmail: ${booking.email}\nBooking Reference: ${booking.id}\nDeposit Paid: $${booking.deposit}\nRemaining Balance: $${Math.max(0,Number(booking.price)-Number(booking.deposit))}`}
function createGoogleCalendarLink(booking){const params=new URLSearchParams({action:'TEMPLATE',text:`Remmybeautyplus – ${booking.service} – ${booking.customerName}`,dates:`${calendarLocal(booking.date,booking.startTime)}/${calendarLocal(booking.date,booking.endTime)}`,ctz:'America/Chicago',location:'Remmybeautyplus Studio – Address provided after booking',details:calendarDescription(booking)});return `https://calendar.google.com/calendar/render?${params.toString()}`}
function downloadICS(booking){const clean=value=>String(value).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;'),settings=RemmyStore.getReminderSettings(),hours=settings.hoursBefore==='custom'?Number(settings.customHours||24):Number(settings.hoursBefore||24),alarm=hours>0?`BEGIN:VALARM\r\nTRIGGER:-PT${hours}H\r\nACTION:DISPLAY\r\nDESCRIPTION:Upcoming Remmybeautyplus appointment\r\nEND:VALARM\r\n`:'';const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Remmybeautyplus//Booking//EN\r\nCALSCALE:GREGORIAN\r\nMETHOD:PUBLISH\r\nBEGIN:VEVENT\r\nUID:${clean(booking.id)}@remmybeautyplus.com\r\nDTSTAMP:${calendarStamp(new Date())}\r\nDTSTART;TZID=America/Chicago:${calendarLocal(booking.date,booking.startTime)}\r\nDTEND;TZID=America/Chicago:${calendarLocal(booking.date,booking.endTime)}\r\nSUMMARY:${clean(`Remmybeautyplus – ${booking.service} – ${booking.customerName}`)}\r\nDESCRIPTION:${clean(calendarDescription(booking))}\r\nLOCATION:${clean('Remmybeautyplus Studio – Address provided after booking')}\r\n${alarm}END:VEVENT\r\nEND:VCALENDAR`,url=URL.createObjectURL(new Blob([ics],{type:'text/calendar;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`remmybeautyplus-${booking.id}.ics`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
window.createGoogleCalendarLink=createGoogleCalendarLink;window.downloadICS=downloadICS;
$('#nextBtn').onclick=()=>{if(validateStep())go(state.step+1)};$('#backBtn').onclick=()=>go(state.step-1);$('#bookingDate').addEventListener('change',event=>{state.date=event.target.value;state.time=null;if(state.date&&state.service){renderQuickDates();renderTimes();updateAside()}clearError()});$('#anotherBtn').onclick=()=>location.reload();const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());$('#bookingDate').min=today.toISOString().split('T')[0];setupPaymentMethods();const hasRequestedService=renderServices();go(hasRequestedService?2:1);
