(function(){
const K={b:'remmy_bookings',d:'remmy_blocked_dates',s:'remmy_services',h:'remmy_business_hours',r:'remmy_reminder_settings'};
const defaults=[{id:'bohemian-braids',name:'Bohemian Braids',price:200,duration:4.5,image:'images/bohemian-braids.webp',description:'Soft curls woven through beautiful braids.',available:true},{id:'twists',name:'Twists',price:160,duration:4,image:'images/remmy-hero.webp',description:'Neat, lightweight twists.',available:true},{id:'crochet',name:'Crochet',price:120,duration:3,image:'images/soft-locs.webp',description:'A versatile protective style.',available:true},{id:'cornrows',name:'Cornrows',price:100,duration:2.5,image:'images/stitch-braids.webp',description:'Creative cornrows with precise parting.',available:true},{id:'soft-locs',name:'Soft Locs',price:180,duration:4.5,image:'images/soft-locs.webp',description:'Natural-looking locs with movement.',available:true},{id:'stitch-braids',name:'Stitch Braids',price:140,duration:3,image:'images/stitch-braids.webp',description:'Crisp stitch details and sculpted rows.',available:true},{id:'individual-scalp-hair',name:'Individual Scalp Hair',price:180,duration:4,image:'images/stitch-braids.webp',description:'Individual scalp styling.',available:true},{id:'human-hair-wigs',name:'Human Hair Wigs',price:250,duration:2,image:'images/bohemian-braids.webp',description:'Human-hair wig preparation and styling.',available:true},{id:'braided-wigs',name:'Braided Wigs',price:200,duration:3,image:'images/remmy-hero.webp',description:'Beautiful custom braided wigs.',available:true},{id:'wig-revamp',name:'Revamping of Old Wigs',price:80,duration:2,image:'images/soft-locs.webp',description:'Restore and restyle an existing wig.',available:true},{id:'blend-wigs',name:'Blend Wigs',price:180,regularPrice:180,salePrice:100,saleActive:true,saleStartDate:'',saleEndDate:'',duration:2.5,image:'images/bohemian-braids.webp',description:'Customized blended wig styling.',available:true}];
const defaultHours={0:{name:'Sunday',available:false,start:'09:00',end:'19:00',times:[]},1:{name:'Monday',available:true,start:'09:00',end:'19:00',times:[]},2:{name:'Tuesday',available:true,start:'09:00',end:'19:00',times:[]},3:{name:'Wednesday',available:false,start:'09:00',end:'19:00',times:[]},4:{name:'Thursday',available:true,start:'09:00',end:'19:00',times:[]},5:{name:'Friday',available:true,start:'09:00',end:'19:00',times:[]},6:{name:'Saturday',available:true,start:'08:00',end:'18:00',times:[]}};
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},write=(key,value)=>(localStorage.setItem(key,JSON.stringify(value)),value),copy=value=>JSON.parse(JSON.stringify(value));
function getBookings(){return read(K.b,[])}function saveBooking(item){write(K.b,[...getBookings(),item]);return item}function updateBooking(id,changes){const items=getBookings(),item=items.find(x=>x.id===id);if(item)Object.assign(item,changes);write(K.b,items);return item}function cancelBooking(id){return updateBooking(id,{status:'cancelled'})}
function getBlockedDates(){return read(K.d,[])}function blockDate(date,reason){const items=getBlockedDates();if(!items.some(x=>x.date===date))items.push({date,reason});return write(K.d,items)}function unblockDate(date){return write(K.d,getBlockedDates().filter(x=>x.date!==date))}
function normalizeService(service){const legacyBlendSale=service.id==='blend-wigs'&&typeof service.saleActive!=='boolean';return {...service,regularPrice:Number(service.regularPrice??service.price??0),price:Number(service.regularPrice??service.price??0),salePrice:legacyBlendSale?100:(service.salePrice==null||service.salePrice===''?null:Number(service.salePrice)),saleActive:legacyBlendSale||Boolean(service.saleActive),saleStartDate:service.saleStartDate||'',saleEndDate:service.saleEndDate||''}}
function getServices(){let saved=read(K.s,null);if(saved&&localStorage.getItem('remmy_sale_version')!=='blend-wigs-100-v1'){saved=saved.map(service=>({...service,regularPrice:Number(service.regularPrice??service.price??0),saleActive:service.id==='blend-wigs',salePrice:service.id==='blend-wigs'?100:service.salePrice??null,saleStartDate:service.id==='blend-wigs'?'':service.saleStartDate||'',saleEndDate:service.id==='blend-wigs'?'':service.saleEndDate||''}));write(K.s,saved);localStorage.setItem('remmy_sale_version','blend-wigs-100-v1')}return (saved||write(K.s,copy(defaults))).map(normalizeService)}function saveService(service){const items=getServices(),normalized=normalizeService(service),i=items.findIndex(x=>x.id===service.id);i<0?items.push(normalized):items[i]=normalizeService({...items[i],...service});write(K.s,items);return normalized}function deleteService(id){return write(K.s,getServices().filter(x=>x.id!==id))}
function getBusinessHours(){return read(K.h,null)||write(K.h,copy(defaultHours))}function saveBusinessHours(hours){return write(K.h,hours)}
function getReminderSettings(){return read(K.r,{customerEnabled:true,adminEnabled:true,emailEnabled:true,smsEnabled:true,hoursBefore:'24',customHours:''})}function saveReminderSettings(settings){return write(K.r,settings)}
window.RemmyStore={getBookings,saveBooking,updateBooking,cancelBooking,getBlockedDates,blockDate,unblockDate,getServices,saveService,deleteService,getBusinessHours,saveBusinessHours,getReminderSettings,saveReminderSettings};
})();
